//! Embeds the application icon and version information in the executable:
//! the icon for title bars, the taskbar, Explorer and Task Manager, and the
//! version information for the name those show ("Framecut", not
//! "framecut.exe").

use std::{env, fs, path::PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=assets/framecut.ico");
    let version = env::var("CARGO_PKG_VERSION").expect("Cargo sets the version");
    let numbers: Vec<u32> = version
        .split(['.', '-', '+'])
        .take(3)
        .map(|part| part.parse().unwrap_or(0))
        .collect();
    let (major, minor, patch) = (numbers[0], numbers[1], numbers[2]);
    let icon = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("assets/framecut.ico");
    let rc = format!(
        r#"// Generated by build.rs.
// GPUI loads icon resource 1 for its windows.
1 ICON "{icon}"

1 VERSIONINFO
FILEVERSION {major},{minor},{patch},0
PRODUCTVERSION {major},{minor},{patch},0
FILEOS 0x40004
FILETYPE 0x1
BEGIN
  BLOCK "StringFileInfo"
  BEGIN
    BLOCK "040904b0"
    BEGIN
      VALUE "FileDescription", "Framecut"
      VALUE "ProductName", "Framecut"
      VALUE "FileVersion", "{version}"
      VALUE "ProductVersion", "{version}"
      VALUE "InternalName", "framecut"
      VALUE "OriginalFilename", "framecut.exe"
    END
  END
  BLOCK "VarFileInfo"
  BEGIN
    VALUE "Translation", 0x409, 1200
  END
END
"#,
        // Resource scripts treat a backslash as an escape.
        icon = icon.display().to_string().replace('\\', "/"),
    );
    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("framecut.rc");
    fs::write(&out, rc).expect("could not write framecut.rc");
    embed_resource::compile(&out, embed_resource::NONE)
        .manifest_optional()
        .expect("could not compile framecut.rc");
}
